server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: stock-client-8082
    prefer-ip-address: true

spring:
  application:
    name: stock-client